oss:
  config:
    enable: true
    endpoint:
    access-key-secret:
    bucket-name:
    access-key-id:
    dir: blog/
server:
  port: 8876

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB